#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HorizonUI

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// Enum HorizonUI.EHorizonDialogueTextOverflowWarpMethod
// NumValues: 0x0003
enum class EHorizonDialogueTextOverflowWarpMethod : uint8
{
	Normal                                   = 0,
	BreakAll                                 = 1,
	EHorizonDialogueTextOverflowWarpMethod_MAX = 2,
};

// Enum HorizonUI.EHorizonDialogueSegmentType
// NumValues: 0x0009
enum class EHorizonDialogueSegmentType : uint8
{
	Invalidated                              = 0,
	Text                                     = 1,
	NewLine                                  = 2,
	Image                                    = 3,
	PaperFlipbook                            = 4,
	Material                                 = 5,
	HyperText                                = 6,
	Custom                                   = 7,
	EHorizonDialogueSegmentType_MAX          = 8,
};

// Enum HorizonUI.EHorizonUIInputMode
// NumValues: 0x0005
enum class EHorizonUIInputMode : uint8
{
	Invalidated                              = 0,
	GameAndUI                                = 1,
	UIOnly                                   = 2,
	GameOnly                                 = 3,
	EHorizonUIInputMode_MAX                  = 4,
};

// ScriptStruct HorizonUI.HorizonDialoguePageInfo
// 0x000C (0x000C - 0x0000)
struct alignas(0x04) FHorizonDialoguePageInfo final
{
public:
	uint8                                         Pad_0[0xC];                                        // 0x0000(0x000C)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FHorizonDialoguePageInfo) == 0x000004, "Wrong alignment on FHorizonDialoguePageInfo");
static_assert(sizeof(FHorizonDialoguePageInfo) == 0x00000C, "Wrong size on FHorizonDialoguePageInfo");

// ScriptStruct HorizonUI.HorizonDialogueBlockInfo
// 0x0038 (0x0038 - 0x0000)
struct alignas(0x08) FHorizonDialogueBlockInfo final
{
public:
	uint8                                         Pad_0[0x38];                                       // 0x0000(0x0038)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FHorizonDialogueBlockInfo) == 0x000008, "Wrong alignment on FHorizonDialogueBlockInfo");
static_assert(sizeof(FHorizonDialogueBlockInfo) == 0x000038, "Wrong size on FHorizonDialogueBlockInfo");

// ScriptStruct HorizonUI.HorizonDialogueSegmentInfo
// 0x01D8 (0x01D8 - 0x0000)
struct FHorizonDialogueSegmentInfo final
{
public:
	class FString                                 Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSlateColor                            ColorAndOpacity;                                   // 0x0010(0x0028)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FSlateFontInfo                         Font;                                              // 0x0038(0x0050)(BlueprintVisible, BlueprintReadOnly, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              ShadowOffset;                                      // 0x0088(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSlateColor                            ShadowColorAndOpacity;                             // 0x0090(0x0028)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	float                                         DialogueMsgSpeed;                                  // 0x00B8(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DialogueMsgWait;                                   // 0x00BC(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C0[0x4];                                       // 0x00C0(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMargin                                PaddingMargin;                                     // 0x00C4(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_D4[0x4];                                       // 0x00D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            HypertextHoveredColor;                             // 0x00D8(0x0028)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FSlateColor                            HypertextVisitedColor;                             // 0x0100(0x0028)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	TSubclassOf<class UHorizonButton>             BackgroundButtonClass;                             // 0x0128(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DialogueSoundVolumeMultiplier;                     // 0x0130(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DialogueSoundPitchMultiplier;                      // 0x0134(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DialogueSoundStartTime;                            // 0x0138(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_13C[0x4];                                      // 0x013C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             DialogueSound;                                     // 0x0140(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_148[0x80];                                     // 0x0148(0x0080)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 EventPayload;                                      // 0x01C8(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FHorizonDialogueSegmentInfo) == 0x000008, "Wrong alignment on FHorizonDialogueSegmentInfo");
static_assert(sizeof(FHorizonDialogueSegmentInfo) == 0x0001D8, "Wrong size on FHorizonDialogueSegmentInfo");
static_assert(offsetof(FHorizonDialogueSegmentInfo, Text) == 0x000000, "Member 'FHorizonDialogueSegmentInfo::Text' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfo, ColorAndOpacity) == 0x000010, "Member 'FHorizonDialogueSegmentInfo::ColorAndOpacity' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfo, Font) == 0x000038, "Member 'FHorizonDialogueSegmentInfo::Font' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfo, ShadowOffset) == 0x000088, "Member 'FHorizonDialogueSegmentInfo::ShadowOffset' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfo, ShadowColorAndOpacity) == 0x000090, "Member 'FHorizonDialogueSegmentInfo::ShadowColorAndOpacity' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfo, DialogueMsgSpeed) == 0x0000B8, "Member 'FHorizonDialogueSegmentInfo::DialogueMsgSpeed' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfo, DialogueMsgWait) == 0x0000BC, "Member 'FHorizonDialogueSegmentInfo::DialogueMsgWait' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfo, PaddingMargin) == 0x0000C4, "Member 'FHorizonDialogueSegmentInfo::PaddingMargin' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfo, HypertextHoveredColor) == 0x0000D8, "Member 'FHorizonDialogueSegmentInfo::HypertextHoveredColor' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfo, HypertextVisitedColor) == 0x000100, "Member 'FHorizonDialogueSegmentInfo::HypertextVisitedColor' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfo, BackgroundButtonClass) == 0x000128, "Member 'FHorizonDialogueSegmentInfo::BackgroundButtonClass' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfo, DialogueSoundVolumeMultiplier) == 0x000130, "Member 'FHorizonDialogueSegmentInfo::DialogueSoundVolumeMultiplier' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfo, DialogueSoundPitchMultiplier) == 0x000134, "Member 'FHorizonDialogueSegmentInfo::DialogueSoundPitchMultiplier' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfo, DialogueSoundStartTime) == 0x000138, "Member 'FHorizonDialogueSegmentInfo::DialogueSoundStartTime' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfo, DialogueSound) == 0x000140, "Member 'FHorizonDialogueSegmentInfo::DialogueSound' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfo, EventPayload) == 0x0001C8, "Member 'FHorizonDialogueSegmentInfo::EventPayload' has a wrong offset!");

// ScriptStruct HorizonUI.HorizonDialogueDialoguePageResult
// 0x0004 (0x0004 - 0x0000)
struct FHorizonDialogueDialoguePageResult final
{
public:
	int32                                         PageIndex;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FHorizonDialogueDialoguePageResult) == 0x000004, "Wrong alignment on FHorizonDialogueDialoguePageResult");
static_assert(sizeof(FHorizonDialogueDialoguePageResult) == 0x000004, "Wrong size on FHorizonDialogueDialoguePageResult");
static_assert(offsetof(FHorizonDialogueDialoguePageResult, PageIndex) == 0x000000, "Member 'FHorizonDialogueDialoguePageResult::PageIndex' has a wrong offset!");

// ScriptStruct HorizonUI.HorizonDialogueHypertextResult
// 0x0078 (0x0078 - 0x0000)
struct FHorizonDialogueHypertextResult final
{
public:
	class UHorizonDialogueMsgTextBlock*           DialogueMsgTextBlock;                              // 0x0000(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SegmentIndex;                                      // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         LineIndex;                                         // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         BlockIndex;                                        // 0x0010(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 HypertextReference;                                // 0x0018(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<class FString, class FString>            UrlEncodeMap;                                      // 0x0028(0x0050)(BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
};
static_assert(alignof(FHorizonDialogueHypertextResult) == 0x000008, "Wrong alignment on FHorizonDialogueHypertextResult");
static_assert(sizeof(FHorizonDialogueHypertextResult) == 0x000078, "Wrong size on FHorizonDialogueHypertextResult");
static_assert(offsetof(FHorizonDialogueHypertextResult, DialogueMsgTextBlock) == 0x000000, "Member 'FHorizonDialogueHypertextResult::DialogueMsgTextBlock' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueHypertextResult, SegmentIndex) == 0x000008, "Member 'FHorizonDialogueHypertextResult::SegmentIndex' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueHypertextResult, LineIndex) == 0x00000C, "Member 'FHorizonDialogueHypertextResult::LineIndex' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueHypertextResult, BlockIndex) == 0x000010, "Member 'FHorizonDialogueHypertextResult::BlockIndex' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueHypertextResult, HypertextReference) == 0x000018, "Member 'FHorizonDialogueHypertextResult::HypertextReference' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueHypertextResult, UrlEncodeMap) == 0x000028, "Member 'FHorizonDialogueHypertextResult::UrlEncodeMap' has a wrong offset!");

// ScriptStruct HorizonUI.HorizonDialogueSegmentInfoStyle
// 0x01F0 (0x01F0 - 0x0000)
struct FHorizonDialogueSegmentInfoStyle final
{
public:
	class FName                                   StyleName;                                         // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         Text;                                              // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FSlateColor>                    ColorAndOpacity;                                   // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FSlateFontInfo>                 Font;                                              // 0x0028(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<int32>                                 FontSize;                                          // 0x0038(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FName>                           TypefaceFontName;                                  // 0x0048(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FVector2D>                      ShadowOffset;                                      // 0x0058(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FSlateColor>                    ShadowColorAndOpacity;                             // 0x0068(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<float>                                 DialogueMsgSpeed;                                  // 0x0078(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<float>                                 DialogueMsgWait;                                   // 0x0088(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FMargin>                        PaddingMargin;                                     // 0x0098(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         HypertextReference;                                // 0x00A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FSlateColor>                    HypertextHoveredColor;                             // 0x00B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FSlateColor>                    HypertextVisitedColor;                             // 0x00C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<TSubclassOf<class UHorizonButton>>     BackgroundButtonClass;                             // 0x00D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UTexture2D>              Texture2D;                                         // 0x00E8(0x0028)(Edit, BlueprintVisible, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UMaterial>               Material;                                          // 0x0110(0x0028)(Edit, BlueprintVisible, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UPaperSprite>            PaperSprite;                                       // 0x0138(0x0028)(Edit, BlueprintVisible, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class USoundBase>              DialogueSound;                                     // 0x0160(0x0028)(Edit, BlueprintVisible, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<float>                                 DialogueSoundVolumeMultiplier;                     // 0x0188(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<float>                                 DialogueSoundPitchMultiplier;                      // 0x0198(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<float>                                 DialogueSoundStartTime;                            // 0x01A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UPaperFlipbook>          PaperFlipbook;                                     // 0x01B8(0x0028)(Edit, BlueprintVisible, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FVector2D>                      ImageSize;                                         // 0x01E0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FHorizonDialogueSegmentInfoStyle) == 0x000008, "Wrong alignment on FHorizonDialogueSegmentInfoStyle");
static_assert(sizeof(FHorizonDialogueSegmentInfoStyle) == 0x0001F0, "Wrong size on FHorizonDialogueSegmentInfoStyle");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, StyleName) == 0x000000, "Member 'FHorizonDialogueSegmentInfoStyle::StyleName' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, Text) == 0x000008, "Member 'FHorizonDialogueSegmentInfoStyle::Text' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, ColorAndOpacity) == 0x000018, "Member 'FHorizonDialogueSegmentInfoStyle::ColorAndOpacity' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, Font) == 0x000028, "Member 'FHorizonDialogueSegmentInfoStyle::Font' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, FontSize) == 0x000038, "Member 'FHorizonDialogueSegmentInfoStyle::FontSize' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, TypefaceFontName) == 0x000048, "Member 'FHorizonDialogueSegmentInfoStyle::TypefaceFontName' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, ShadowOffset) == 0x000058, "Member 'FHorizonDialogueSegmentInfoStyle::ShadowOffset' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, ShadowColorAndOpacity) == 0x000068, "Member 'FHorizonDialogueSegmentInfoStyle::ShadowColorAndOpacity' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, DialogueMsgSpeed) == 0x000078, "Member 'FHorizonDialogueSegmentInfoStyle::DialogueMsgSpeed' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, DialogueMsgWait) == 0x000088, "Member 'FHorizonDialogueSegmentInfoStyle::DialogueMsgWait' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, PaddingMargin) == 0x000098, "Member 'FHorizonDialogueSegmentInfoStyle::PaddingMargin' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, HypertextReference) == 0x0000A8, "Member 'FHorizonDialogueSegmentInfoStyle::HypertextReference' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, HypertextHoveredColor) == 0x0000B8, "Member 'FHorizonDialogueSegmentInfoStyle::HypertextHoveredColor' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, HypertextVisitedColor) == 0x0000C8, "Member 'FHorizonDialogueSegmentInfoStyle::HypertextVisitedColor' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, BackgroundButtonClass) == 0x0000D8, "Member 'FHorizonDialogueSegmentInfoStyle::BackgroundButtonClass' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, Texture2D) == 0x0000E8, "Member 'FHorizonDialogueSegmentInfoStyle::Texture2D' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, Material) == 0x000110, "Member 'FHorizonDialogueSegmentInfoStyle::Material' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, PaperSprite) == 0x000138, "Member 'FHorizonDialogueSegmentInfoStyle::PaperSprite' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, DialogueSound) == 0x000160, "Member 'FHorizonDialogueSegmentInfoStyle::DialogueSound' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, DialogueSoundVolumeMultiplier) == 0x000188, "Member 'FHorizonDialogueSegmentInfoStyle::DialogueSoundVolumeMultiplier' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, DialogueSoundPitchMultiplier) == 0x000198, "Member 'FHorizonDialogueSegmentInfoStyle::DialogueSoundPitchMultiplier' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, DialogueSoundStartTime) == 0x0001A8, "Member 'FHorizonDialogueSegmentInfoStyle::DialogueSoundStartTime' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, PaperFlipbook) == 0x0001B8, "Member 'FHorizonDialogueSegmentInfoStyle::PaperFlipbook' has a wrong offset!");
static_assert(offsetof(FHorizonDialogueSegmentInfoStyle, ImageSize) == 0x0001E0, "Member 'FHorizonDialogueSegmentInfoStyle::ImageSize' has a wrong offset!");

// ScriptStruct HorizonUI.HorizonDialogueLineInfo
// 0x0028 (0x0028 - 0x0000)
struct alignas(0x08) FHorizonDialogueLineInfo final
{
public:
	uint8                                         Pad_0[0x28];                                       // 0x0000(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FHorizonDialogueLineInfo) == 0x000008, "Wrong alignment on FHorizonDialogueLineInfo");
static_assert(sizeof(FHorizonDialogueLineInfo) == 0x000028, "Wrong size on FHorizonDialogueLineInfo");

}

